name: Trigger auto deployment for container-app-gpnkn2ynouwse

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-gpnkn2ynouwse-AutoDeployTrigger-bb58d4d8-8c79-488c-b15a-365c476eab79.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGPNKN2YNOUWSE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGPNKN2YNOUWSE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGPNKN2YNOUWSE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGPNKN2YNOUWSE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGPNKN2YNOUWSE_REGISTRY_PASSWORD }}
          containerAppName: container-app-gpnkn2ynouwse
          resourceGroup: appspacesragapp9be68764
          imageToBuild: default/container-app-gpnkn2ynouwse:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


